To begin, let's first initialize an 8x8 matrix with all elements set to 0. You can do this using the zeros() function from the numpy library.

In [30]:
import numpy as np

confusion_matrix = np.zeros((8, 8))

# **1) Metrics for the best Model on Microsoft Azure Machine Learning Studio ✅**

Iterate through each row and column of the matrix and set the value of the element at that position to the desired value. Confusion Matrix for Microsoft Azure Machine Learning Studio model

In [31]:
#Row 0: 47 4 5 13 4 2 18 10
confusion_matrix[0][0] = 47
confusion_matrix[0][1] = 4
confusion_matrix[0][2] = 5
confusion_matrix[0][3] = 13
confusion_matrix[0][4] = 4
confusion_matrix[0][5] = 2
confusion_matrix[0][6] = 18
confusion_matrix[0][7] = 10
#Row 1: 2 70 1 4 0 6 0 20
confusion_matrix[1][0] = 2
confusion_matrix[1][1] = 70
confusion_matrix[1][2] = 1
confusion_matrix[1][3] = 4
confusion_matrix[1][4] = 0
confusion_matrix[1][5] = 6
confusion_matrix[1][6] = 0
confusion_matrix[1][7] = 20
#Row 2: 17 2 48 4 8 8 10 6
confusion_matrix[2][0] = 17
confusion_matrix[2][1] = 2
confusion_matrix[2][2] = 48
confusion_matrix[2][3] = 4
confusion_matrix[2][4] = 8
confusion_matrix[2][5] = 8
confusion_matrix[2][6] = 10
confusion_matrix[2][7] = 6
#Row 3: 15 6 2 52 15 5 4 4
confusion_matrix[3][0] = 15
confusion_matrix[3][1] = 6
confusion_matrix[3][2] = 2
confusion_matrix[3][3] = 52
confusion_matrix[3][4] = 15
confusion_matrix[3][5] = 5
confusion_matrix[3][6] = 4
confusion_matrix[3][7] = 4
#Row 4: 8 1 7 17 58 6 6 0
confusion_matrix[4][0] = 8
confusion_matrix[4][1] = 1
confusion_matrix[4][2] = 7
confusion_matrix[4][3] = 17
confusion_matrix[4][4] = 58
confusion_matrix[4][5] = 6
confusion_matrix[4][6] = 6
confusion_matrix[4][7] = 0
#Row 5: 6 4 8 2 5 49 18 11
confusion_matrix[5][0] = 6
confusion_matrix[5][1] = 4
confusion_matrix[5][2] = 8
confusion_matrix[5][3] = 2
confusion_matrix[5][4] = 5
confusion_matrix[5][5] = 49
confusion_matrix[5][6] = 18
confusion_matrix[5][7] = 11
#Row 6: 12 1 7 6 9 22 44 2
confusion_matrix[6][0] = 12
confusion_matrix[6][1] = 1
confusion_matrix[6][2] = 7
confusion_matrix[6][3] = 6
confusion_matrix[6][4] = 9
confusion_matrix[6][5] = 22
confusion_matrix[6][6] = 44
confusion_matrix[6][7] = 2
#Row 7: 13 11 4 2 3 7 6 57
confusion_matrix[7][0] = 13
confusion_matrix[7][1] = 11
confusion_matrix[7][2] = 4
confusion_matrix[7][3] = 2
confusion_matrix[7][4] = 3
confusion_matrix[7][5] = 7
confusion_matrix[7][6] = 6
confusion_matrix[7][7] = 57

 print the matrix to check if it has been filled in correctly.

In [32]:
print(confusion_matrix)

[[47.  4.  5. 13.  4.  2. 18. 10.]
 [ 2. 70.  1.  4.  0.  6.  0. 20.]
 [17.  2. 48.  4.  8.  8. 10.  6.]
 [15.  6.  2. 52. 15.  5.  4.  4.]
 [ 8.  1.  7. 17. 58.  6.  6.  0.]
 [ 6.  4.  8.  2.  5. 49. 18. 11.]
 [12.  1.  7.  6.  9. 22. 44.  2.]
 [13. 11.  4.  2.  3.  7.  6. 57.]]


This code will create a confusion matrix and calculate the sensitivity, specificity, false positive rate, false negative rate, positive predictive value, negative predictive value, accuracy, F1 score, and AUC for each of the 8 classes.

In [33]:
import pandas as pd
from sklearn.metrics import roc_auc_score

# Replace `n_classes` with the number of classes in your data
n_classes = 8

# Calculate sensitivity (recall) for each class
sensitivity = confusion_matrix.diagonal() / confusion_matrix.sum(axis=1)

# Calculate specificity for each class
specificity = (np.sum(confusion_matrix, axis=1) - confusion_matrix.diagonal()) / np.sum(confusion_matrix, axis=1)

# Calculate false positive rate for each class
fpr = 1 - specificity

# Calculate false negative rate for each class
fnr = 1 - sensitivity

# Calculate positive predictive value for each class
ppv = confusion_matrix.diagonal() / np.sum(confusion_matrix, axis=0)

# Calculate negative predictive value for each class
npv = (np.sum(confusion_matrix, axis=0) - confusion_matrix.diagonal()) / np.sum(confusion_matrix, axis=0)

# Calculate accuracy
accuracy = np.sum(confusion_matrix.diagonal()) / np.sum(confusion_matrix)

# Calculate F1 score for each class
f1 = 2 * (ppv * sensitivity) / (ppv + sensitivity)

# AUC from Azure AutoML
auc = 0.85502


# Create a dataframe to store the results
metrics = pd.DataFrame({"Sensitivity": sensitivity, "Specificity": specificity, "FPR": fpr, "FNR": fnr, "PPV": ppv, "NPV": npv, "F1": f1})
print(metrics)
print(f"Accuracy: {accuracy:.2f}")
print(f"AUC: {auc:.2f}")

   Sensitivity  Specificity       FPR       FNR       PPV       NPV        F1
0     0.456311     0.543689  0.456311  0.543689  0.391667  0.608333  0.421525
1     0.679612     0.320388  0.679612  0.320388  0.707071  0.292929  0.693069
2     0.466019     0.533981  0.466019  0.533981  0.585366  0.414634  0.518919
3     0.504854     0.495146  0.504854  0.495146  0.520000  0.480000  0.512315
4     0.563107     0.436893  0.563107  0.436893  0.568627  0.431373  0.565854
5     0.475728     0.524272  0.475728  0.524272  0.466667  0.533333  0.471154
6     0.427184     0.572816  0.427184  0.572816  0.415094  0.584906  0.421053
7     0.553398     0.446602  0.553398  0.446602  0.518182  0.481818  0.535211
Accuracy: 0.52
AUC: 0.86


# **2) Metrics for the best Model on Google Vertex AI ✅**

Iterate through each row and column of the matrix and set the value of the element at that position to the desired value. Confusion Matrix for Google Vertex AI model

In [34]:
#Row 0: 
confusion_matrix[0][0] = 24
confusion_matrix[0][1] = 1
confusion_matrix[0][2] = 6
confusion_matrix[0][3] = 0
confusion_matrix[0][4] = 0
confusion_matrix[0][5] = 3
confusion_matrix[0][6] = 2
confusion_matrix[0][7] = 4

#Row 1:
confusion_matrix[1][0] = 0
confusion_matrix[1][1] = 29
confusion_matrix[1][2] = 0
confusion_matrix[1][3] = 1
confusion_matrix[1][4] = 0
confusion_matrix[1][5] = 0
confusion_matrix[1][6] = 1
confusion_matrix[1][7] = 7
#Row 2:
confusion_matrix[2][0] = 2
confusion_matrix[2][1] = 1
confusion_matrix[2][2] = 28
confusion_matrix[2][3] = 0
confusion_matrix[2][4] = 3
confusion_matrix[2][5] = 1
confusion_matrix[2][6] = 1
confusion_matrix[2][7] = 2
#Row 3:
confusion_matrix[3][0] = 2
confusion_matrix[3][1] = 0
confusion_matrix[3][2] = 1
confusion_matrix[3][3] = 22
confusion_matrix[3][4] = 5
confusion_matrix[3][5] = 1
confusion_matrix[3][6] = 2
confusion_matrix[3][7] = 5
#Row 4:
confusion_matrix[4][0] = 0
confusion_matrix[4][1] = 0
confusion_matrix[4][2] = 2
confusion_matrix[4][3] = 3
confusion_matrix[4][4] = 29
confusion_matrix[4][5] = 1
confusion_matrix[4][6] = 3
confusion_matrix[4][7] = 0
#Row 5:
confusion_matrix[5][0] = 1
confusion_matrix[5][1] = 1
confusion_matrix[5][2] = 4
confusion_matrix[5][3] = 0
confusion_matrix[5][4] = 1
confusion_matrix[5][5] = 25
confusion_matrix[5][6] = 4
confusion_matrix[5][7] = 2
#Row 6:
confusion_matrix[6][0] = 0
confusion_matrix[6][1] = 0
confusion_matrix[6][2] = 0
confusion_matrix[6][3] = 1
confusion_matrix[6][4] = 1
confusion_matrix[6][5] = 6
confusion_matrix[6][6] = 29
confusion_matrix[6][7] = 1
#Row 7:
confusion_matrix[7][0] = 1
confusion_matrix[7][1] = 1
confusion_matrix[7][2] = 2
confusion_matrix[7][3] = 2
confusion_matrix[7][4] = 1
confusion_matrix[7][5] = 0
confusion_matrix[7][6] = 1
confusion_matrix[7][7] = 30

 print the matrix to check if it has been filled in correctly.

In [35]:
print(confusion_matrix)

[[24.  1.  6.  0.  0.  3.  2.  4.]
 [ 0. 29.  0.  1.  0.  0.  1.  7.]
 [ 2.  1. 28.  0.  3.  1.  1.  2.]
 [ 2.  0.  1. 22.  5.  1.  2.  5.]
 [ 0.  0.  2.  3. 29.  1.  3.  0.]
 [ 1.  1.  4.  0.  1. 25.  4.  2.]
 [ 0.  0.  0.  1.  1.  6. 29.  1.]
 [ 1.  1.  2.  2.  1.  0.  1. 30.]]


This code will create a confusion matrix and calculate the sensitivity, specificity, false positive rate, false negative rate, positive predictive value, negative predictive value, accuracy, F1 score, and AUC for each of the 8 classes.

In [36]:
import pandas as pd

# Replace `n_classes` with the number of classes in your data
n_classes = 8

# Calculate sensitivity (recall) for each class
sensitivity = confusion_matrix.diagonal() / confusion_matrix.sum(axis=1)

# Calculate specificity for each class
specificity = (np.sum(confusion_matrix, axis=1) - confusion_matrix.diagonal()) / np.sum(confusion_matrix, axis=1)

# Calculate false positive rate for each class
fpr = 1 - specificity

# Calculate false negative rate for each class
fnr = 1 - sensitivity

# Calculate positive predictive value for each class
ppv = confusion_matrix.diagonal() / np.sum(confusion_matrix, axis=0)

# Calculate negative predictive value for each class
npv = (np.sum(confusion_matrix, axis=0) - confusion_matrix.diagonal()) / np.sum(confusion_matrix, axis=0)

# Calculate accuracy
accuracy = np.sum(confusion_matrix.diagonal()) / np.sum(confusion_matrix)

# Calculate F1 score for each class
f1 = 2 * (ppv * sensitivity) / (ppv + sensitivity)

# From google vertex AI:
auc = 0.9

# Create a dataframe to store the results
metrics = pd.DataFrame({"Sensitivity": sensitivity, "Specificity": specificity, "FPR": fpr, "FNR": fnr, "PPV": ppv, "NPV": npv, "F1": f1})
print(metrics)
print(f"Accuracy: {accuracy:.2f}")
print(f"AUC: {auc:.2f}")

   Sensitivity  Specificity       FPR       FNR       PPV       NPV        F1
0     0.600000     0.400000  0.600000  0.400000  0.800000  0.200000  0.685714
1     0.763158     0.236842  0.763158  0.236842  0.878788  0.121212  0.816901
2     0.736842     0.263158  0.736842  0.263158  0.651163  0.348837  0.691358
3     0.578947     0.421053  0.578947  0.421053  0.758621  0.241379  0.656716
4     0.763158     0.236842  0.763158  0.236842  0.725000  0.275000  0.743590
5     0.657895     0.342105  0.657895  0.342105  0.675676  0.324324  0.666667
6     0.763158     0.236842  0.763158  0.236842  0.674419  0.325581  0.716049
7     0.789474     0.210526  0.789474  0.210526  0.588235  0.411765  0.674157
Accuracy: 0.71
AUC: 0.90


# **3) Metrics for the best Model on Amazon SageMaker Studio ✅**

Iterate through each row and column of the matrix and set the value of the element at that position to the desired value. Confusion Matrix for the Amazon SageMaker Studio model


***Please Note that these confusion matrix values are not the actual values for the Amazon SageMaker best run model.***

In [40]:
confusion_matrix[0][0] = 34
confusion_matrix[0][1] = 4
confusion_matrix[0][2] = 5
confusion_matrix[0][3] = 13
confusion_matrix[0][4] = 4
confusion_matrix[0][5] = 2
confusion_matrix[0][6] = 18
confusion_matrix[0][7] = 10

confusion_matrix[1][0] = 2
confusion_matrix[1][1] = 56
confusion_matrix[1][2] = 1
confusion_matrix[1][3] = 4
confusion_matrix[1][4] = 0
confusion_matrix[1][5] = 6
confusion_matrix[1][6] = 0
confusion_matrix[1][7] = 20

confusion_matrix[2][0] = 17
confusion_matrix[2][1] = 2
confusion_matrix[2][2] = 39
confusion_matrix[2][3] = 4
confusion_matrix[2][4] = 8
confusion_matrix[2][5] = 8
confusion_matrix[2][6] = 10
confusion_matrix[2][7] = 6

confusion_matrix[3][0] = 15
confusion_matrix[3][1] = 6
confusion_matrix[3][2] = 2
confusion_matrix[3][3] = 39
confusion_matrix[3][4] = 15
confusion_matrix[3][5] = 5
confusion_matrix[3][6] = 4
confusion_matrix[3][7] = 4

confusion_matrix[4][0] = 8
confusion_matrix[4][1] = 1
confusion_matrix[4][2] = 7
confusion_matrix[4][3] = 17
confusion_matrix[4][4] = 50
confusion_matrix[4][5] = 6
confusion_matrix[4][6] = 6
confusion_matrix[4][7] = 0

confusion_matrix[5][0] = 6
confusion_matrix[5][1] = 4
confusion_matrix[5][2] = 8
confusion_matrix[5][3] = 10
confusion_matrix[5][4] = 5
confusion_matrix[5][5] = 40
confusion_matrix[5][6] = 12
confusion_matrix[5][7] = 11

confusion_matrix[6][0] = 12
confusion_matrix[6][1] = 1
confusion_matrix[6][2] = 7
confusion_matrix[6][3] = 6
confusion_matrix[6][4] = 15
confusion_matrix[6][5] = 2
confusion_matrix[6][6] = 38
confusion_matrix[6][7] = 2

confusion_matrix[7][0] = 13
confusion_matrix[7][1] = 11
confusion_matrix[7][2] = 4
confusion_matrix[7][3] = 10
confusion_matrix[7][4] = 3
confusion_matrix[7][5] = 7
confusion_matrix[7][6] = 6
confusion_matrix[7][7] = 54

 print the matrix to check if it has been filled in correctly.

In [41]:
print(confusion_matrix)

[[34.  4.  5. 13.  4.  2. 18. 10.]
 [ 2. 56.  1.  4.  0.  6.  0. 20.]
 [17.  2. 39.  4.  8.  8. 10.  6.]
 [15.  6.  2. 39. 15.  5.  4.  4.]
 [ 8.  1.  7. 17. 50.  6.  6.  0.]
 [ 6.  4.  8. 10.  5. 40. 12. 11.]
 [12.  1.  7.  6. 15.  2. 38.  2.]
 [13. 11.  4. 10.  3.  7.  6. 54.]]


This code will create a confusion matrix and calculate the sensitivity, specificity, false positive rate, false negative rate, positive predictive value, negative predictive value, accuracy, F1 score, and AUC for each of the 8 classes.

In [42]:
import pandas as pd

# Replace `n_classes` with the number of classes in your data
n_classes = 8

# Calculate sensitivity (recall) for each class
sensitivity = confusion_matrix.diagonal() / confusion_matrix.sum(axis=1)

# Calculate specificity for each class
specificity = (np.sum(confusion_matrix, axis=1) - confusion_matrix.diagonal()) / np.sum(confusion_matrix, axis=1)

# Calculate false positive rate for each class
fpr = 1 - specificity

# Calculate false negative rate for each class
fnr = 1 - sensitivity

# Calculate positive predictive value for each class
ppv = confusion_matrix.diagonal() / np.sum(confusion_matrix, axis=0)

# Calculate negative predictive value for each class
npv = (np.sum(confusion_matrix, axis=0) - confusion_matrix.diagonal()) / np.sum(confusion_matrix, axis=0)

# Calculate accuracy
accuracy = np.sum(confusion_matrix.diagonal()) / np.sum(confusion_matrix)

# Calculate F1 score for each class
f1 = 2 * (ppv * sensitivity) / (ppv + sensitivity)

# AUC from Amazon SageMaker
auc = 0.41


# Create a dataframe to store the results
metrics = pd.DataFrame({"Sensitivity": sensitivity, "Specificity": specificity, "FPR": fpr, "FNR": fnr, "PPV": ppv, "NPV": npv, "F1": f1})
print(metrics)
print(f"Accuracy: {accuracy:.2f}")
print(f"AUC: {auc:.2f}")

   Sensitivity  Specificity       FPR       FNR       PPV       NPV        F1
0     0.377778     0.622222  0.377778  0.622222  0.317757  0.682243  0.345178
1     0.629213     0.370787  0.629213  0.370787  0.658824  0.341176  0.643678
2     0.414894     0.585106  0.414894  0.585106  0.534247  0.465753  0.467066
3     0.433333     0.566667  0.433333  0.566667  0.378641  0.621359  0.404145
4     0.526316     0.473684  0.526316  0.473684  0.500000  0.500000  0.512821
5     0.416667     0.583333  0.416667  0.583333  0.526316  0.473684  0.465116
6     0.457831     0.542169  0.457831  0.542169  0.404255  0.595745  0.429379
7     0.500000     0.500000  0.500000  0.500000  0.504673  0.495327  0.502326
Accuracy: 0.47
AUC: 0.41
